/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "motd.h"


void motd_prog_1(char *host, char *msg)
{
	CLIENT *clnt;
  clnt = clnt_create (host, MOTD_PROG, MOTD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

  if(msg) {
    // add

    void  *add_result = add_1(&msg, clnt);
    if (add_result == (void *) NULL) {
      clnt_perror (clnt, "call failed");
    }

  } else {
    // print all msgs

    char *count_1_arg;
    int *np = count_1((void*)&count_1_arg, clnt);
    if ( np == (int *) NULL ) {
      clnt_perror (clnt, "call failed");
      exit( EXIT_FAILURE );
    }
    
    for ( int i = 0; i < *np; i++ ) {
      char **spp = get_1(&i, clnt);
      if ( spp == (char **) NULL ) {
        clnt_perror (clnt, "call failed");
        exit( EXIT_FAILURE );
      }
      printf( "%s\n", *spp );
    }
  }

	clnt_destroy (clnt);
}


int main (int argc, char *argv[])
{
	if (argc < 2 || argc > 3 ) {
    printf ("usage: %s server_host [message]\n", argv[0]);
    exit (1);
  }

  if ( argc == 3 ) {
    motd_prog_1( argv[ 1 ], argv[ 2 ] );
  } else {
    motd_prog_1( argv[ 1 ], NULL );
  }

  exit( EXIT_SUCCESS );
}
