/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "motd.h"
#include <string.h>

// Maximum number of messages in the history.
#define HISTORY_MAX 3

// Maximum length of a message.
#define MESSAGE_MAX 60


// History of recent messages.
static char mList[ HISTORY_MAX ][ MESSAGE_MAX + 1 ];

// Current number of messages.
static int mCount = 0;


int *
count_1_svc(void *argp, struct svc_req *rqstp)
{
  return &mCount;
}

char **
get_1_svc(int *argp, struct svc_req *rqstp)
{
	// A static variable for holding our return value (a pointer).
  // We return the address of this variable, so it's marked static.
  static char * result;

  // Return error if we get an invalid index.
  if ( *argp < 0 || *argp >= mCount ) {
    result = "error";
    return &result;
  }

  // Return the address of the selected message.
  result = mList[ *argp ];
  return &result;
}

void *
add_1_svc(char **argp, struct svc_req *rqstp)
{
  static void * result;

  // maximum message count -> shift messages down
  if ( mCount == HISTORY_MAX ) {
    for ( int i = mCount - 1; i > 0; i-- ) {
      strncpy( mList[ i ], mList[ i - 1 ], MESSAGE_MAX );
      mList[ i ][ MESSAGE_MAX ] = '\0';
      // strcpy( mList[ i + 1 ], mList[ i ] );
    
    }

  } else {
    mCount++;
  }
  
  // copy new message to the top of list
  strncpy( mList[ 0 ], *argp, MESSAGE_MAX );

  // null terminate the string
  mList[ 0 ][ MESSAGE_MAX ] = '\0';

  // strcpy( mList[ mCount - 1 ], *argp );

  return &result;
}
